### ISSUE TITLE
buffer.js TypeError 'must start with number, buffer, array or string'

### ISSUE THREAD

**Issue by kaiwa** [jonaswitt/max-api#1]
```
coffee app.coffee 
[[01.48.2017 18:02:38]] [DIR] { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
[[01.48.2017 18:02:38]] [ERROR] js-bson: Failed to load c++ bson extension, using pure JS version
[[01.48.2017 18:02:38]] [LOG] Looking for cubes...
[[01.48.2017 18:02:40]] [LOG] Found 1 cube(s)
[[01.48.2017 18:02:40]] [LOG] Listening on http://localhost:3000/...
buffer.js:141
    throw new TypeError('must start with number, buffer, array or string');
    ^

TypeError: must start with number, buffer, array or string
  at fromObject (buffer.js:141:11)
  at new Buffer (buffer.js:62:10)
  at [object Object].Parser.parseMetadata (/tmp/max-api/lib/parser.coffee:74:18)
  at [object Object].Parser.parseLine (/tmp/max-api/lib/parser.coffee:53:6)
  at Stream.<anonymous> (/tmp/max-api/lib/parser.coffee:41:12)
  at Stream.stream.write (/tmp/max-api/node_modules/through/index.js:26:11)
  at Stream.ondata (stream.js:31:26)
  at emitOne (events.js:77:13)
  at Stream.emit (events.js:169:7)
  at drain (/tmp/max-api/node_modules/through/index.js:36:16)
  at Stream.stream.queue.stream.push (/tmp/max-api/node_modules/through/index.js:45:5)
  at emit (/tmp/max-api/node_modules/split/index.js:36:14)
  at next (/tmp/max-api/node_modules/split/index.js:48:7)
  at Stream.<anonymous> (/tmp/max-api/node_modules/split/index.js:53:5)
  at Stream.stream.write (/tmp/max-api/node_modules/through/index.js:26:11)
  at Socket.ondata (_stream_readable.js:528:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)
```

```
$ node -v
v4.2.6
$ coffee -v
CoffeeScript version 1.9.3
$ npm -v
3.5.2
```

**Comment by kaiwa** [comment]
Ah, es lag wohl irgendwie daran dass der cube noch nicht richtig initialisiert (?) war. Nachdem ich ihn mit einem Windows-Rechner eingerichtet habe funktioniert es korrekt. `info_fields[2]` war zuvor undefined.

**Comment by jonaswitt** [comment]
Hi! Gut zu wissen, dass es doch geht. Ich habe das System leider nicht mehr im Einsatz und kann es aktuell nicht nachvollziehen. Ich habe immer nur mit bereits eingerichteten Cubes getestet.
